import pytest
from sklearn.linear_model import LinearRegression, QuantileRegressor
from sklearn.ensemble import HistGradientBoostingRegressor
from source.ensemble.stack_generalization.hyperparam_optimization.optimization import optimize_model, initialize_model

